cabal-version:   3.0
name:            x16-apple-division
version:         0.1.0.0
license:         GPL-2.0-only
license-file:    LICENSE
author:          Toby Thain
maintainer:      toby@telegraphics.net
category:        Puzzles
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall -Wextra -O

executable knapsack
    import:           warnings
    main-is:          knapsack.hs
    build-depends:    containers ^>=0.7, base ^>=4.21.2.0
    hs-source-dirs:   .
    default-language: Haskell2010
